### ISSUE TITLE
Marking objects as sensitive 

### ISSUE THREAD

**Issue by matheusbrat** [untitaker/python-sensitive-variables#3]
Hello @untitaker ,

How are you? Have you considered having some special markers which the `_scrub_locals_from_traceback` could understand and automatically clean? 

One of the use cases I'm thinking right now is related to microservices which has a thin client library. A few services might use this libraries and the response is a dict. I thought on creating a new class `SensitiveDict(UserDict)` which could have a `_sensitive_fields` property so other services using a client library could leverage on the SensitiveDict and simply use the decorator `sensitive_variables` and the sensitive fields would be automatically hidden for a service response. 

Going a bit further, maybe it would be nice to have a `Sensitive` class so we could mark any object as sensitive and the scrub could handle this.  

Have you put any thought on this? Do you think something like this could fit on this library? Are there features you have been thinking to add to it?

**Comment by untitaker** [comment]
I would rather put this information somehow into the decorator rather than force people to change their local variables to a different type.

For example:

```python
@sensitive_variables(my_sensitive_dict={"foo": None})
```

to specify that there is a `MutableMapping` that needs scrubbing.

Or alternately we can let people define a callback to make it more obvious what is really going on:

```python
def scrub_dictionary(d):
    d.pop("foo", None)

@sensitive_variables(my_sensitive_dict=scrub_dictionary)
```

**Comment by matheusbrat** [comment]
I think this can be considered as done since #4 was merged and gives the user power to implement more specific solutions.
