### ISSUE TITLE
Question related to names conditional

### ISSUE THREAD

**Issue by matheusbrat** [untitaker/python-sensitive-variables#7]
Do you think we could change this logic a bit? I belive we should only call clear when "not names AND not custom_scrub_fn" as if the user is passing a custom_scrub_fn he might not pass the variables.

https://github.com/untitaker/python-sensitive-variables/blob/751c87f64c05a15140b95f80c03583fa3f82bce8/sensitive_variables/__init__.py#L100

**Comment by untitaker** [comment]
Yes that makes sense, though I think this means that we should split up the if-else into two ifs. Could you prepare a PR for this?
